### ISSUE TITLE
update docs to point to GitHub rather than Sourceforge

### ISSUE THREAD

**Issue by gregcaporaso** [pycogent/pycogent#1]
From @GavinHuttley by email:

We need to modify the displayed docs http://pycogent.org/#contacts-and-contributing so that bug-reports/forums etc.. point to the correct places on github. Same for the developer page. More generally we need to purge all references to sourceforge, updating them to be github counterparts.

NOTE: this purging needs to be done in the actual rst docs in the repo, so that when we build docs for the next release etc ... we don't have to revisit this.

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
