### ISSUE TITLE
No 1.9 release tarball available

### ISSUE THREAD

**Issue by nieder** [pycogent/pycogent#100]
There is no 1.9 release tarball available anywhere.  Github, SF.net and PyPi all still list 1.5.3 as the last release.  And there's also no 1.9 tag on Github. Is commit 8bd7b7b the equivalent for the 1.9 release?

**Comment by GavinHuttley** [comment]
There [cogent page at PyPI](https://pypi.python.org/pypi/cogent/1.9) does show a [tarball](https://pypi.python.org/packages/03/9e/a7156965da5edc34c3c07661c3b4bc4259caa3d9dcecaa5f7f3ff51eecd7/cogent-1.9.tar.gz#md5=7d9f28cd17664c1cd18c568fc53060d6).

**Comment by nieder** [comment]
Huh.  Weird.  The search https://pypi.python.org/pypi?%3Aaction=search&term=cogent&submit=search only shows 1.5.3 for me. Thanks for the direct pointer. Sorry about the noise.
