### ISSUE TITLE
Test failures for cd-hit when trying to build Debian package

### ISSUE THREAD

**Issue by tillea** [pycogent/pycogent#101]
Hi,
I wanted to upgrade the Debian package to the latest upstream version.  Unfortunately there are 4 failures related to cd-hit.  I snipped the error messages and attached it to this bug report.

[cogent_cd-hit_test_failures.txt](https://github.com/pycogent/pycogent/files/442593/cogent_cd-hit_test_failures.txt)

It would be helpful to track down the issue if I would know what exact command whould be run on the system to possibly give some further hints about the issue but I have no idea how to get the plain command string.

Kind regards

```
  Andreas.
```

**Comment by GavinHuttley** [comment]
@wasade could you comment on this please

**Comment by wasade** [comment]
@tillea, what version of cd-hit was used? The [app controller](https://github.com/pycogent/pycogent/blob/master/cogent/app/cd_hit.py#L2) only supports `3.1.1`

**Comment by tillea** [comment]
Hi Daniel,

On Wed, Aug 31, 2016 at 01:33:49PM -0700, Daniel McDonald wrote:
> @tillea, what version of cd-hit was used? The [app controller](https://github.com/pycogent/pycogent/blob/master/cogent/app/cd_hit.py#L2) only supports `3.1.1` 

The latest version of cd-hit: 4.6.6.  Is there any chance to adapt
python-cogent to the recent version?

Kind regards

      Andreas.

-- 
http://fam-tille.de

**Comment by wasade** [comment]
I don't have bandwidth right now to do this, sorry

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
