### ISSUE TITLE
Test failure with FastTree  2.1.9

### ISSUE THREAD

**Issue by tillea** [pycogent/pycogent#102]
Hi,

I'm working on the pycogent packaging for Debian.  When running the test suite with FastTree version 2.1.9 installed I get:
# 
## FAIL: test_build_tree_from_alignment (test_app.test_fasttree.FastTreeTests)

Traceback (most recent call last):
  File "/build/python-cogent-1.9/tests/test_app/test_fasttree.py", line 50, in test_build_tree_from_alignment
    self.assertEqual(o.Name,e.Name)
  File "/build/python-cogent-1.9/cogent/util/unit_test.py", line 316, in failUnlessEqual
    (msg or 'Got %s, but expected %s' % (`observed`, `expected`))
AssertionError: Got '0.409', but expected '0.466'

---

Kind regards

```
     Andreas.
```

**Comment by tillea** [comment]
Hi Gavin,

On Thu, Sep 15, 2016 at 05:23:47PM -0700, GavinHuttley wrote:
> This is again an issue with being an unsupported version of an application. Unfortunately, @wasade is the maintainer of this and since he has indicated he has no time for updating other app controllers I suspect this applies to this one also.
> 
> We would of course welcome any patches you might like to contribute to address this! **BUT**, please note the python 2 PyCogent series is in maintenance mode.

Thanks for the explanation - specifically about Pythono 2 series.  I was
even wondering whether some Python3 support might be available.  For the
moment I deal with this by simply skipping the failed tests and document
what tests have skipped.  I think this is slightly better than before
since there was some time when tests were not run at all in the Debian
packaging process.
 
> [PyCogent3](https://bitbucket.org/pycogent3/cogent3) (python 3 compatible, available, but not yet released) has dropped *all* application controllers, amongst numerous other changes. This is because there are now a multitude of alternatives to application controllers than what PyCogent contains.

I would consider uploading a pycogent3 package to Debian experimental.
This might enable early testing for Debian users while clearly stating
that it is not for production.

Kind regards

       Andreas.

-- 
http://fam-tille.de

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
