### ISSUE TITLE
Random failures of test suite

### ISSUE THREAD

**Issue by tillea** [pycogent/pycogent#103]
Hi,
there is a bug report in the [Debian bug tracking sysem](https://bugs.debian.org/846078) which reports segfaults occuring "randomly" when running unit tests.  I admit I do not have the slightest idea how to track this down but it affects the fact whether pycogent will be part of the next Debian stable release or not.  It might help if you could provide information about tests that could contain some randomness and we could simply disable these specific test(s).
Kind regards
        Andreas.

**Comment by GavinHuttley** [comment]
Could you run the tests using the verbose flag, e.g.

```python
$ ./run_tests -v
```
That will show each test run, helping identify the exact test where the issue occurs. My prediction is it will be in the struct module (for handling 3D structures).

**Comment by tillea** [comment]
Hi Gavin,

On Mon, Nov 28, 2016 at 02:33:03PM -0800, GavinHuttley wrote:
> Could you run the tests using the verbose flag, e.g.
> 
> ```python
> $ ./run_tests -v
> ```
> That will show each test run, helping identify the exact test where the issue occurs. My prediction is it will be in the struct module (for handling 3D structures).

Thanks a lot for this quick and helpful response.  I've prepared a
package featuring this verbose output and uploaded it to the Debian
mirror.  Santiago, I wonder whether you can run your tests with
python-cogent_1.9-5 to possibly reproduce the failures.  This should
give a hint what actual test might cause the problem.

Kind regards

       Andreas.

-- 
http://fam-tille.de

**Comment by tillea** [comment]
Hi again,
while there is no evidence that the issue is connected to the random failures on amd64 I'd like to inform you about problems with the test suite on other architectures which all try to build pycogent Debian packages on so called autobuilders.
There are [build logs](https://buildd.debian.org/status/package.php?p=python-cogent) for all architectures and currently we observe two failures:

On mips:
   inputs_from_dict2D makes an array object and PhyloNode list ... ok
   test_upgma_cluster (test_cluster.test_UPGMA.UPGMATests)
   UPGMA_cluster clusters nodes based on info in a matrix with UPGMA ... ok
   test_2 (test_cluster.test_nmds.NMDSTests)
   l19 data should give stress below .13 ... ok
   test_3 (test_cluster.test_nmds.NMDSTests)
   l19 data should give stress below .13 in multi-D ... 

And on powerpc:
   test_crystal (test_struct.test_asa.asaTest)
   compares asa within unit cell. ... ok
   test_uc (test_struct.test_asa.asaTest)
   compares asa within unit cell. ... ok
   test_uc2 (test_struct.test_asa.asaTest) ... Segmentation fault

My usual way to deal with this was to exclude the actual test for the architecture that failed to run the test - but put possibly you are interested and might draw sensible conclusions for your code.

Kind regards, Andreas.

**Comment by GavinHuttley** [comment]
Not seeing a mips failure in the above. The struct module is at fault as predicted. As the maintainer of that module is no longer active, it has been dropped from [PyCogent3](https://bitbucket.org/pycogent3/cogent3) I suggest just commenting out that test.
As per my previous response regarding support for this version of PyCogent, we are in minimal maintenance mode (meaning, support for core capabilities only). The Python3 compatible PyCogent3 is the future. It's currently in alpha and no formal release has yet been made.

**Comment by tillea** [comment]
Hi,
the bug reporter Santiago Vila has done a new series of tests with the verbose tests.  He wrote:

I built 1.9-5 two hundred times and it failed 16 times. I put the build logs here to not clutter the BTS:
https://people.debian.org/~sanvila/python-cogent/

The first one of the logs says:

  test_checkpointing (test_maths.test_optimisers.OptimiserTestCase) ... ok
  test_get_max_eval_count (test_maths.test_optimisers.OptimiserTestCase)
  return the evaluation count from optimisation ... FAIL
  test_global (test_maths.test_optimisers.OptimiserTestCase) ... ok
  ...
  ======================================================================
  FAIL: test_get_max_eval_count (test_maths.test_optimisers.OptimiserTestCase)
  return the evaluation count from optimisation
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/<<PKGBUILDDIR>>/tests/test_maths/test_optimisers.py", line 88, in test_get_max_eval_count
      self.assertTrue(e > 500)
  AssertionError: False is not true
  
  ----------------------------------------------------------------------
  Ran 3595 tests in 60.648s

  FAILED (failures=1)

The second log shows:


  FAIL: test_init (test_seqsim.test_sequence_generators.UnpairedRegionTests)
  Unpaired region should generate right freqs, even after change
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/<<PKGBUILDDIR>>/tests/test_seqsim/test_sequence_generators.py", line 486, in test_init
      self.assertSimilarFreqs(observed, expected)
    File "/<<PKGBUILDDIR>>/cogent/util/unit_test.py", line 530, in assertSimilarFreqs
      (msg or 'p-value %s, G-test p %s' % (`pvalue`, `p`))
  AssertionError: p-value 0.01, G-test p 0.0073005635654467792


However, that's not the only type of failure.  I've also seen:

  compares asa within unit cell. ... ok
  test_uc (test_struct.test_asa.asaTest)
  compares asa within unit cell. ... ok
  test_uc2 (test_struct.test_asa.asaTest) ... Segmentation fault


I confirm that I understood the low maintenance status of the current pycogent version and I perfectly agree that a Python3 version would be preferable.  However, I think it makes sense to keep the current version alive to fullfill the need of users who depend from pycogent.

Please feel free to ask me for further information.

Kind regards,  Andreas.

PS: Sorry for messing up the layout - no idea how I can simply put verbose text. :-(

**Comment by genomematt** [comment]
There is a decorator for permitted failures in unit test.  I suggest just adding this to the relevant tests so the failures are graceful

**Comment by tillea** [comment]
Hi Matthew,

On Tue, Dec 06, 2016 at 03:08:39PM -0800, Matthew Wakefield wrote:
> There is a decorator for permitted failures in unit test.  I suggest just adding this to the relevant tests so the failures are graceful 

Thanks for the hint but could you please give a specific example on a
random test for the usage of the decorator?

Thanks

      Andreas.

-- 
http://fam-tille.de

**Comment by genomematt** [comment]
Expected failures use the expectedFailure()<https://docs.python.org/2/library/unittest.html#unittest.expectedFailure> decorator.

class ExpectedFailureTestCase(unittest.TestCase):
    @unittest.expectedFailure
    def test_fail(self):
        self.assertEqual(1, 0, "broken")

These then don't count as failure.

--=-=--=-=--=-=--=-=--=-=--
Matthew Wakefield
matthew@wakefield.id.au<mailto:matthew@wakefield.id.au>
+61 402 916 018

On 7 Dec. 2016, at 6:27 pm, Andreas Tille <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Matthew,

On Tue, Dec 06, 2016 at 03:08:39PM -0800, Matthew Wakefield wrote:
> There is a decorator for permitted failures in unit test. I suggest just adding this to the relevant tests so the failures are graceful

Thanks for the hint but could you please give a specific example on a
random test for the usage of the decorator?

Thanks

Andreas.

--
http://fam-tille.de

-

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
