### ISSUE TITLE
cogent Genome does not fetch data from ensembl version 86 and onwards

### ISSUE THREAD

**Issue by vladie0** [pycogent/pycogent#104]
Dear developers, 

Pycogent Genome is unable to fetch data from Ensembl 86 and 87,

Is it possible to fix this issue ? 
Thanks in advance

**Comment by GavinHuttley** [comment]
The Python 2 version of PyCogent is in maintenance now. The project has been superseded by [PyCogent3](https://bitbucket.org/pycogent3/cogent3). The ensembl querying capabilities have been split out into their own project [ensembldb3](https://bitbucket.org/pycogent3/ensembldb3). Please note there are significant API changes.
The ensembldb3 documentation [is here](http://ensembldb3.readthedocs.io/en/latest/).

**Comment by vladie0** [comment]
Dear GavinHuttley, 

Thank you for your quick response. Will the current version of pycogent become compatible with Ensembl 86 and 87. For my project I cannot use python 3, If not, I'll have to look for another alternative

Thanks in advance

**Comment by GavinHuttley** [comment]
We will not be made compatible unless someone submits a patch. (It you were interested, you could look at the changes made to get ensembldb3 working with Ensembl 86+.)
Out of interest, what applications/modules are you using that preclude Python3?

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.

For the ensembl querying, please see https://github.com/cogent3/ensembldb3
