### ISSUE TITLE
update code to work with Python 3.x

### ISSUE THREAD

**Issue by fizwit** [pycogent/pycogent#106]
setup.py build " exited with exitcode 1 and output:
  File "setup.py", line 61
    print "Failed to build html due to ImportErrors for sphinx"
                                                              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by GavinHuttley** [comment]
[PyCogent3 exists](https://bitbucket.org/pycogent3/cogent3), but note it's currently only in alpha and has been significantly changed.

This branch of PyCogent is in maintenance mode only.
