### ISSUE TITLE
[Question] Releasing code under BSD instead of GPL

### ISSUE THREAD

**Issue by campenr** [pycogent/pycogent#107]
Hello,

I had a question regarding the current licensing status of PyCogent code. PyCogent is licensed under the GPL, however on the [scikit-bio](https://github.com/biocore/scikit-bio) page there is mention of the PyCogent code having been released under the new BSD license. I am wondering whether this release of PyCogent code under the BSD is project wide, or only for specific parts, and whether this BSD licensed code is available for anyone or only the scikit-bio group. I ask because I can not find any mention of re-releasing PyCogent under the BSD other than the one mention on the scikit-bio.

Any clarification of the current license status of PyCogent would be greatly appreciated.

Cheers
Richard

**Comment by GavinHuttley** [comment]
hi,

all PyCogent developers agreed that we would release the entire project under BSD.

Also note, there's a port of [PyCogent to Python3 here](https://bitbucket.org/pycogent3/cogent3).

cheers, gavin

**Comment by campenr** [comment]
Hi Gavin,

Thank you for your response and the link to the Python 3 port.

Is there a copy of the new BSD license that I can include with my project that you can direct me to? If not do you have any suggestions what to include regarding license information for code pulled from PyCogent? The specific functionality that I am making use of is the [NMDS](https://github.com/pycogent/pycogent/blob/master/cogent/cluster/nmds.py) code which is not currently implemented in PyCogent3, and the source code file still retains the GPL license info.

Cheers
Richard

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
