### ISSUE TITLE
Trim terminal stop codons with partial sequences

### ISSUE THREAD

**Issue by santiagoha** [pycogent/pycogent#108]
Hi everyone, 

I am getting an error when using the function `withoutTerminalStopCodons` with the argument `allow_partial=True`. It seems that it is not reading the argument, this is the error message I am getting:
`assert len(codons) % 3 == 0, "seq length not divisible by 3"`. 

Any suggestion is very welcome, thanks!

**Comment by GavinHuttley** [comment]
This is fixed in cogent3. [cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
