### ISSUE TITLE
Sorting `envs`/`env_names` in `fast_unifrac`/`_fast_unifrac_setup` should be optional

### ISSUE THREAD

**Issue by riemannzetagambit** [pycogent/pycogent#110]
I use cogent's `fast_unifrac` utility in  a custom wrapper function so that it plays nice with the dataframes we use. I rely on the fact that the `distance_matrix` returned has the same ordering as the columns of the dataframe I pass to the wrapper, which I thought would be guaranteed by passing the desired order (I've been using an `OrderedDict`) in the `envs` argument of `fast_unifrac`/`_fast_unifrac_setup`. However, in line 190 of the fast_unifrac module

https://github.com/pycogent/pycogent/blob/8675f5c6e5edbf56205027a207aab9b3c232fdee/cogent/maths/unifrac/fast_unifrac.py#L190

the `env_names` are sorted automatically. Is there any intention to change this behavior, so that the order in `envs` matches the order returned in the 'distance_matrix' tuple of `fast_unifrac`?

If not, I can try my hand at a PR.

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
