### ISSUE TITLE
Pycogent on a local database

### ISSUE THREAD

**Issue by MarijkeVM** [pycogent/pycogent#111]
We would like to use Pycogent in our project to receive additional information of certain genes.
When we query the external Ensembl database with pycogent, our script produces the needed information.

However, when we query against a local copy of the database we receive an error. Upon providing the gene symbol, it produces the error that the column "status" is unknow" After looking into the code, we found that it is trying to access this column in the gene table. However, this status column only appears in the external_db table in our copy of the database.

Could you maybe explain why this is no issue when acccessing the external database? Is there a postprocessing step required after installing a local copy in order to connect the tables gene and external_db?

Thank you for your time!

**Comment by MarijkeVM** [comment]
I just realized this is due to a difference in the versions. Release 89 still contains a "status" column in the gene table while version 90 and higher do not. The problem will likely be solved upon installing release 89 as a local copy.

**Comment by GavinHuttley** [comment]
Please note that PyCogent for Python 2 is no longer being actively maintained. You are encouraged to migrate to [PyCogent3](https://bitbucket.org/pycogent3/cogent3), the python 3 port of PyCogent. There are numerous API changes, outlined on the wiki at that repo. Of particular relevance to this ticket is that the ensembl code is now in a separate project, called [ensembldb3](https://bitbucket.org/pycogent3/ensembldb3). That project includes admin tools for downloading and installing ensembl that you might find useful.
