### ISSUE TITLE
Incompatibility with latest matplotlib

### ISSUE THREAD

**Issue by tillea** [pycogent/pycogent#112]
Hi,
the Debian package received a [bug report](https://alioth-lists.debian.net/pipermail/debian-med-packaging/2018-May/062792.html) about a conflict with latest matplotlib.  Please see the [full log of the test suite](https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-cogent/334120/log.gz) which boils down to issues like:

    ======================================================================
    ERROR: test_consistent_gap_degen_handling (test_core.test_sequence.ModelSequenceTests)
    gap degen character should be treated consistently
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/autopkgtest-lxc.0szesf8z/downtmp/autopkgtest_tmp/tests/test_core/test_sequence.py", line 660, in test_consistent_gap_degen_handling
        self.assertEqual(dna.stripBadAndGaps(), raw_ungapped)
      File "/usr/lib/python2.7/dist-packages/cogent/core/sequence.py", line 1251, in stripBadAndGaps
        valid_indices -= self._data == i
    TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

    ======================================================================
    ERROR: test_stripBadAndGaps (test_core.test_sequence.ModelSequenceTests)
    Sequence stripBadAndGaps should remove gaps and bad chars
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/autopkgtest-lxc.0szesf8z/downtmp/autopkgtest_tmp/tests/test_core/test_sequence.py", line 882, in test_stripBadAndGaps
        self.assertEqual(r.stripBadAndGaps(), 'ACGGRN')
      File "/usr/lib/python2.7/dist-packages/cogent/core/sequence.py", line 1251, in stripBadAndGaps
        valid_indices -= self._data == i
    TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

    ======================================================================
    ERROR: test_binary_dist_jaccard (test_maths.test_distance_transform.functionTests)
    tests binary_dist_jaccard
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/tmp/autopkgtest-lxc.0szesf8z/downtmp/autopkgtest_tmp/tests/test_maths/test_distance_transform.py", line 347, in test_binary_dist_jaccard
        sparse1expected = dist_manhattan(self.sparse1.astype(bool))
      File "/usr/lib/python2.7/dist-packages/cogent/maths/distance_transform.py", line 675, in dist_manhattan
        dists[i,j] = dists[j,i] = sum(abs(r1 - datamtx[j]))
    TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

    ======================================================================
    FAIL: test_dictarray.rst
    Doctest: test_dictarray.rst
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 2226, in runTest
        raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for test_dictarray.rst
      File "test_dictarray.rst", line 0

It would be nice if you could adapt cogent to latest matplotlib.
Kind regards, Andreas.

**Comment by llimeht** [comment]
The incompatibility is with numpy not matplotlib. The two attached patches are *probably* sufficient since the operations were most likely XORs, but since the meaning of bool subtraction isn't obvious to me, some more careful analysis is warranted. 

[numpy_xor.patch](https://github.com/pycogent/pycogent/files/2072984/numpy_xor.patch.txt)
[numpy-doctests.patch](https://github.com/pycogent/pycogent/files/2072985/numpy-doctests.patch.txt)

(Can turn this into a PR if you like)

**Comment by tillea** [comment]
Hi Stuart,

On Tue, Jun 05, 2018 at 03:32:46PM +0000, Stuart Prescott wrote:
> The incompatibility is with numpy not matplotlib. The two attached patches are *probably* sufficient since the operations were most likely XORs, but since the meaning of bool subtraction isn't obvious to me, some more careful analysis is warranted. 

Thanks for your input.
 
> (Can turn this into a PR if you like)

PR would be great IMHO since it makes it more visible for comments from upstream.

Thanks a lot, Andreas.

**Comment by tillea** [comment]
Hi again,
now there is another issue - this time probably really with matplotlib [reported](https://bugs.debian.org/915908) to Debian:

    FAIL: test_set_figure_size_long_labels
    (test_draw.test_distribution_plots.DistributionPlotsTests)
    Test setting a figure size that has really long labels.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File
    "/tmp/autopkgtest-lxc.gcsqih4m/downtmp/autopkgtest_tmp/tests/test_draw/test_distribution_plots.py",
    line 511, in test_set_figure_size_long_labels
        "Warning: could not automatically resize plot to make room for "
      File "/usr/lib/python2.7/dist-packages/cogent/util/unit_test.py", line
    316, in failUnlessEqual
        (msg or 'Got %s, but expected %s' % (`observed`, `expected`))
    AssertionError: Got '', but expected "Warning: could not automatically
    resize plot to make room for axes labels and plot title. This can happen
    if the labels or title are extremely long and the plot size is too
    small. Your plot may have its labels and/or title cut-off. To fix this,
    try increasing the plot's size (in inches) and try again."

    ----------------------------------------------------------------------
    Ran 3527 tests in 54.981s

    FAILED (failures=1)

I'd be really happy if you could comment on this.
BTW, in some other conversation you said there will be a port to Python3.  Do you have any estimation for a release date?
Kind regards, Andreas.

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
