### ISSUE TITLE
Please port to Python3

### ISSUE THREAD

**Issue by tillea** [pycogent/pycogent#115]
Hello,
the Debian Med team is maintaining pycogent for official Debian. The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL. If you are interested that we continue to maintain pycogent in official Debian (and that users of other modern distributions will have no problems to install pycogent on their systems) I'd recommend you port your code to Python3. I've read several announcements about a Python3 port of pycogent in the past but so far I can not see any hint for a release.
I also found a hint to [pycogent3](https://bitbucket.org/pycogent3/cogent3/).  If this is the future official location of pycogent and development will continue there please specify this more prominently.
Kind regards, Andreas.

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
