### ISSUE TITLE
TestCase.assertFloatEqual doesn't handle infinity correctly

### ISSUE THREAD

**Issue by jairideout** [pycogent/pycogent#16]
`TestCase.assertFloatEqual` sees `inf` and `-inf` as equal, while `TestCase.assertEqual` does not.

For example:

`self.assertFloatEqual(float('inf'), float('-inf'))` passes, but when comparing `inf` to `-inf` this way:

```
>>> float('inf') == float('-inf')
False
```

I think the correct behavior is to treat `inf` and `-inf` as being different.

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
