### ISSUE TITLE
Why isn't Windows supported?

### ISSUE THREAD

**Issue by finswimmer** [pycogent/pycogent#20]
Hello,
why isn't windows official supported. Because it isn't tested there or are special things well known that they won't work?

finswimmer

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.

cogent3 DOES support Windows!
