### ISSUE TITLE
Core db doesn't exist for 'Mustela putorius furo'

### ISSUE THREAD

**Issue by jergosh** [pycogent/pycogent#32]
I'm trying to fetch some sequences for ferret genes:

```
from cogent.db.ensembl import Genome, Species
Species.amendSpecies('Mustela putorius furo', 'Ferret')
ferret = Genome(Species='ferret', Release=71)
ferret.getGeneByStableId(StableId="ENSMPUG00000000068")
```

but I'm getting a "RuntimeError: core db doesn't exist for 'Mustela putorius furo' on 'ensembldb.ensembl.org'" error message.

I implemented the same in Perl and it seems to work fine:

```
use Bio::EnsEMBL::Registry;

my $registry = 'Bio::EnsEMBL::Registry';

$registry->load_registry_from_db(
    -host => 'ensembldb.ensembl.org',
    -user => 'anonymous'
    );

my $gene_adaptor  = $registry->get_adaptor( 'ferret', 'Core', 'Gene' );
$gene = $gene_adaptor->fetch_by_stable_id('ENSMPUG00000000068');
```

**Comment by ccreagor** [comment]
Hi, I'm trying to do the exact same thing, only my organism is Amphimedon queenslandica:

`Species.amendSpecies('Amphimedon queenslandica', 'sponge')
assert Species.getCommonName('Amphimedon queenslandica') == 'sponge'
sponge = Genome(Species='sponge', Release=36, account=None)`

I switched to repo version and it still doesn't work. What might be wrong? Any help appreciated.
