### ISSUE TITLE
Exception in DenseAligment __init__ method

### ISSUE THREAD

**Issue by krcurtis** [pycogent/pycogent#37]
Hi,

I'm novice user of QIIME, which is using pycogent version 1.5.3, and I get an exception in DenseAlignment __init__(). After starting up the debugger the error is with the type conversion:

p( type(self.SeqData.astype(self.Alphabet.ArrayType)) )  
*** ValueError: ValueError('setting an array element with a sequence.',)

Looking at self.SeqData, it is a numpy.ndarray containing lists:
(Pdb) p(type(self.SeqData[0]))
<type 'list'>

The type to convert to is
(Pdb) p(self.Alphabet.ArrayType) 
<type 'numpy.uint8'>

So it seems reasonable that numpy would throw an error when trying to convert a list into a byte.  I looked at some of QIIME's align seq tests, and SeqData[0] in those tests was a <type 'numpy.ndarray'>, and SeqData was a 2D array.

Any thoughts on why SeqData is an array of lists? Is this something pycogent normally does? Is it getting confused somewhere along the line? Perhaps QIIME is not passing some extra information, but what would it be?  Thanks for you help.

For reference, here's my stack trace:
 /usr/lib/python2.7/pdb.py(1314)main()
-> pdb._runscript(mainpyfile)
  /usr/lib/python2.7/pdb.py(1233)_runscript()
-> self.run(statement)
  /usr/lib/python2.7/bdb.py(387)run()
-> exec cmd in globals, locals
  <string>(1)<module>()
  /home/krcurtis/microbiome_software/packages/qiime-1.6.0/scripts/align_seqs.py(3)<module>()
-> from __future__ import division
  /home/krcurtis/microbiome_software/packages/qiime-1.6.0/scripts/align_seqs.py(188)main()
-> log_path=log_path,failure_path=failure_path)
  /home/krcurtis/lib/python2.7/site-packages/qiime/align_seqs.py(240)__call__()
-> aligned=DenseAlignment)
  /home/krcurtis/lib/python2.7/site-packages/cogent/__init__.py(108)LoadSeqs()
-> label_to_name=label_to_name, **constructor_kw)
> /home/krcurtis/lib/python2.7/site-packages/cogent/core/alignment.py(1959)__init__()
-> self.SeqData.astype(self.Alphabet.ArrayType))

**Comment by GavinHuttley** [comment]
Closing as this is seriously out-of-date and has received no response. Suggest the Qiime forums if this is still an issue.
