### ISSUE TITLE
uclust application controller does not properly report out of memory errors

### ISSUE THREAD

**Issue by wasade** [pycogent/pycogent#40]
See below, the traceback indicates a mismatch in version while the error itself is OOM.

bash-4.1$ cat POTU_zzB2_0.e269325
Traceback (most recent call last):
  File "/Users/antoniog/bin/qiime/scripts/pick_otus.py", line 771, in <module>
    main()
  File "/Users/antoniog/bin/qiime/scripts/pick_otus.py", line 730, in main
    failure_path=failure_path)
  File "/Users/antoniog/bin/qiime/qiime/pick_otus.py", line 1502, in __call__
    HALT_EXEC=HALT_EXEC)
  File "/Users/antoniog/bin/qiimeSoftware/pycogent-1.5.3-release/lib/python2.7/site-packages/cogent/app/uclust.py", line 550, in get_clusters_from_fasta_filepath
    raise ApplicationError, ('Error running uclust. Possible causes are '
cogent.app.util.ApplicationError: Error running uclust. Possible causes are unsupported version (current supported version is v1.2.22) is installed or improperly formatted input file was provided
mv: cannot stat `ucrC/uclust_ref_picked_otus/POTU_zzB2_/POTU_zzB2_.0_otus.log': No such file or directory
mv: cannot stat `ucrC/uclust_ref_picked_otus/POTU_zzB2_/POTU_zzB2_.0_otus.txt': No such file or directory
mv: cannot stat `ucrC/uclust_ref_picked_otus/POTU_zzB2_/POTU_zzB2_.0_failures.txt': No such file or directory

bash-4.1$ head tmpmPWVgbgEwgNq3Z0ygRhg.txt
uclust v1.2.22q
(C) Copyright 2009-10 Robert C. Edgar
Licensed ONLY for use in PyNAST and QIIME.
02:37 8.3Gb  100.0% Reading lib, 18190 seeds
02:37 8.2Gb    0.0%                         
Out of memory mymalloc(1032822), curr 8.59e+09 bytes
---Fatal error---
Out of memory, mymalloc(1032822), curr 8.59e+09 bytes

uclust --maxrejects 500 --input /scratch/antoniog/tmp/UclustExactMatchFilterioADRhQpsPGhSWdod4Bt.fasta --id 0.97 --w 12 --stepwords 20 --usersort --maxaccepts 20 --libonly --stable_sort --lib /scratch/antoniog/nomic/dbs/interest.fna --uc ucrC/uclust_ref_picked_otus/POTU_zzB2_/POTU_zzB2_1_clusters.uc

**Comment by GavinHuttley** [comment]
Closing here as pursued on Qiime forum.
