### ISSUE TITLE
additional tests of cogent.maths.stats.rarefaction.subsample_multinomial

### ISSUE THREAD

**Issue by jairideout** [pycogent/pycogent#53]
Moving this issue here from the QIIME issue tracker (original issue can be found [here](https://github.com/qiime/qiime/issues/201)).

Original issue description written by @gregcaporaso:

*added this in a rush to speed up rob's ASM analysis - rob wrote the function, greg wrote the test, and don't have time to do additional testing right now.*

**Comment by GavinHuttley** [comment]
Closing this given age of ticket.
