### ISSUE TITLE
To get the DNA sequence for a given ENSP

### ISSUE THREAD

**Issue by alanwilter** [pycogent/pycogent#69]
Essentially, I would love a method to do what's described in this perl code using Ensembl Perl API:

``` perl
use warnings;
use Bio::EnsEMBL::Registry;
my $registry = 'Bio::EnsEMBL::Registry';
$registry->load_registry_from_db( -host => 'ensembldb.ensembl.org', -user => 'anonymous' );
my $transcript_adaptor = $registry->get_adaptor( 'Human', 'Core', 'Transcript' );
my $transcript = $transcript_adaptor->fetch_by_translation_stable_id('ENSP00000411070');
print $transcript->translateable_seq, "
";
```

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.

For the ensembl querying, please see https://github.com/cogent3/ensembldb3
