### ISSUE TITLE
How to get a region of genome from ensembl? 

### ISSUE THREAD

**Issue by lbxjollier** [pycogent/pycogent#75]
Sorry if this is not the right place to post this question. It is related to the documentation of the package. 

Given a location of the human genome (e.g. Chr17, nucleotide number 79477190), would there be a way to retrieve a region of the genome surrounding it? 

I know getRegion is perhaps the right command but I'm not quite sure about the parameters (see below)  
getRegion(self, region=None, CoordName=None, Start=None, End=None, Strand=None, ensembl_coord=False) 

Which flag specifies chromosome number? And does Start and End specify the the start and end of region that will be retrieved? I'm most grateful if somebody could explaine those parameters to me. 

Thanks in advance for any information!

**Comment by raonyguimaraes** [comment]
I have a strange problem with this command:

    for gene in human.getRegion(CoordName="X", Start=128115082, End=130192058).getFeatures(feature_types=['Gene']):
        print gene

cogent/db/ensembl/genome.py", line 386, in _get_gene_features
    coord = asserted_one(get_coord_conversion(coord, target_coord.CoordType, self.CoreDb))[1]
UnboundLocalError: local variable 'coord' referenced before assignment

What am I doing wrong ?

**Comment by GavinHuttley** [comment]
Closing this since the last comment has been submitted as a separate bug report.
