### ISSUE TITLE
Non-stationary model which, at equilibrium, would be reversible

### ISSUE THREAD

**Issue by sarahparks** [pycogent/pycogent#85]
Hi,

I would like to set up a model which is non-stationary, but would be reversible if it were at equilibrium. So, for nucleotides, there should be 8 parameters for the reversible model (which is constant over the whole tree), and another 3 for the distribution at the root, which can be different to the equilibrium distribution of the model. Is there a way to do this in pycogent?

Thank you,

Sarah

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
