### ISSUE TITLE
Retrieving all gene IDs for a given species

### ISSUE THREAD

**Issue by gawbul** [pycogent/pycogent#86]
Is it possible to retrieve a list of gene IDs for a given species using pycogent? Similar to EnsEMBL's Perl API `$gene_adaptor->list_stable_ids()` method?

I was looking over the `genome.py` code, but couldn't see an equivalent method.

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.

For the ensembl querying, please see https://github.com/cogent3/ensembldb3
