### ISSUE TITLE
License of pycogent

### ISSUE THREAD

**Issue by yuharasatoshi** [pycogent/pycogent#88]
Is the license fee required for commercial use (sequencing service)?

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.

For the ensembl querying, please see https://github.com/cogent3/ensembldb3
