### ISSUE TITLE
error with compara and recent Ensembl releases

### ISSUE THREAD

**Issue by lassancejm** [pycogent/pycogent#89]
I get a systematic error when invoking Compara and the getRelatedGenes function from Ensembl release above 67.

$ compara =Compara (['human','mouse','rat'], account=None, Release=81)

$ orthologs = compara.getRelatedGenes(StableId='ENSMUSG00000041147', Relationship= 'ortholog_one2one')

ProgrammingError: (ProgrammingError) (1146, "Table 'ensembl_compara_81.member' doesn't exist") 'DESCRIBE member' ()

**Comment by GavinHuttley** [comment]
That has been fixed in the github repo version. Please upgrade your version of PyCogent. You can do this either by downloading the zip from the projects [github main page](https://github.com/pycogent/pycogent), or via pip. For the latter do:

```shell
$ pip install https://github.com/pycogent/pycogent/archive/master.zip --upgrade
```

**Comment by lassancejm** [comment]
Thanks for your input, it works now
