### ISSUE TITLE
BirthDeathModel/RangeNode: tree nodes are not labelled.

### ISSUE THREAD

**Issue by ropermpv** [pycogent/pycogent#92]
Cogent version:
'1.5.3-dev'

Problem:
Tree simulation described at http://pycogent.org/examples/seqsim_tree_sim.html results in a tree with
no labels.

Code:
from cogent.seqsim.birth_death import BirthDeathModel, ExtinctionError,TooManyTaxaError

b = BirthDeathModel(BirthProb=0.2, DeathProb=0.1, TimePerStep=0.03,MaxTaxa=5)
while True:
    try:
        t = b(exact=True)
    except (ExtinctionError, TooManyTaxaError):
        pass
    else:
        break

print t

Output:
(((((:0.03,:0.03):0.03,:0.06):0.06,:0.12):0.18,:0.3):0.09)

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
