### ISSUE TITLE
About taxon_ids_to_names_and_lineages() in ncbi.py

### ISSUE THREAD

**Issue by sulsj** [pycogent/pycogent#95]
Hi~

I've tried to use the function, "taxon_ids_to_names_and_lineages()" and found it's useful. 

My question is how to get the rank information, like phylum, genus, etc. For example, if there is a gi, 87247983, I can get 

'uncultured archaeon', 'cellular organisms; Archaea; environmental samples'

but I would like to have an output like 

'uncultured archaeon', 'cellular organisms; Archaea; ; ; ; ; environmental samples'

which preserves each rank location as blank if no information is available. 

Is there any way I can do that? 

Thanks, 
Seung

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
