### ISSUE TITLE
Can node labels be parsed as edge values?

### ISSUE THREAD

**Issue by lczech** [pycogent/pycogent#96]
Hi all,

@jhcepas, @stamatak and I are currently working on an update to our preprint on [incorrect mapping of support values after tree rooting](http://biorxiv.org/content/early/2015/12/25/035360).

We [submitted an issue](https://github.com/biocore/scikit-bio/issues/1355) at the scikit-bio repo, and were asked to also submit this here.

The [important question](https://github.com/biocore/scikit-bio/issues/1355#issuecomment-220272604) is:

How much effort would it be to offer a flag for `LoadTree` that would read metadata in form of inner node labels in Newick files directly to some field of the branches instead of the nodes? It could default to "read to nodes", so that existing code won't break. (This is just a suggestion based on our experience with users who do not know about the issue.)

Remark: In the linked issue at scikit-bio, we speak of branch support values, but this generally affects all branch-related data.

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
