### ISSUE TITLE
error message when running own pdb files

### ISSUE THREAD

**Issue by mlynekg3** [pycogent/pycogent#97]
Dear All, if I use pdb files downloaded from pdb the python script I got is running fine. However if I use my own pdbs refined wih phenix or refmac I get following error.

I am pretty sure that pycogent reads some remarks from the pdb which are just in pdb files from http://www.rcsb.org/pdb/home/home.do.

python CC_analysis_local.py test.pdb
test.pdb
Traceback (most recent call last):
  File "CC_analysis_local.py", line 25, in <module>
    conts = contact.contacts_xtra(model, xtra_key='CNT', search_limit=4.0, contact_mode='diff_chain', symmetry_mode='uc', crystal_mode=2)
  File "/usr/local/lib/python2.7/dist-packages/cogent/struct/contact.py", line 162, in contacts_xtra
    result = _prepare_contacts(query, **cnt_kwargs) # calculate CONTACTS
  File "/usr/local/lib/python2.7/dist-packages/cogent/struct/contact.py", line 82, in _prepare_contacts
    sh['uc_fmx'], \
KeyError: 'uc_fmx'

Any help how to fix this is highly appreciated. Thanks in advance, best regards Georg.

**Comment by GavinHuttley** [comment]
I suggest emailing the maintainer of that module. Their email address is mpc4p _at_ virginia _dot_ edu

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
