### ISSUE TITLE
Table 'ensembl_compara_84.member' doesn't exist") 'DESCRIBE member' ()"

### ISSUE THREAD

**Issue by chirrie** [pycogent/pycogent#98]
Iam trying to extract orthologs from Ensembl 84 , but I am getting this error. Could someone suggest a solution to this...

file "/export/apps/python/2.7.8/lib/python2.7/site-packages/MySQL_python-1.2.4b4-py2.7-linux-x86_64.egg/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
sqlalchemy.exc.ProgrammingError: (ProgrammingError) (1146, "Table 'ensembl_compara_84.member' doesn't exist") 'DESCRIBE member' ()"

**Comment by GavinHuttley** [comment]
Can you confirm that you are using the github version (1.5.3-dev)? If so, this is likely a change in the Ensembl schema for their compara tables.

Could you please post a code sample illustrating the problem.

**Comment by GavinHuttley** [comment]
I'm now pretty sure this is due to you using an older version of PyCogent. If you have git installed you can try the following install using `pip`:
```bash
$ pip install git+https://github.com/pycogent/pycogent.git
```
If you don't have git installed, go to the main [PyCogent github page](https://github.com/pycogent/pycogent), click the "Clone or download" button and select "Download zip". Then
```bash
$ pip install /path/to/pycogent-master.zip 
```
Please let me know if this resolves the issue.

**Comment by chirrie** [comment]
https://github.com/pycogent/pycogent
<https://owa.cgiar.org/owa/redir.aspx?SURL=TkAh5WEjFgj_d4DO9UFdkwhb2B0xQGeDVbs8Qfw-E0FvYMQcTYjTCGgAdAB0AHAAcwA6AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AcAB5AGMAbwBnAGUAbgB0AC8AcAB5AGMAbwBnAGUAbgB0AA..&URL=https%3a%2f%2fgithub.com%2fpycogent%2fpycogent>
. Actually I did instal the Pycogent library from the mentioned source. And
it is version 1.5.3.

**Comment by GavinHuttley** [comment]
needs to be 1.5.3-dev

**Comment by GavinHuttley** [comment]
I'm closing this as there has been no further response.
