### ISSUE TITLE
Using pip to upgrade gives this error : Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UvtXdd/cogent/

### ISSUE THREAD

**Issue by miklou** [pycogent/pycogent#99]
I've tried on 2 different systems so far and got the exact same error.
This one is from a Ubuntu system, the other was a ArchLinux.

Take note it's an upgrade `pip install -U cogent` and current installed version is the github dev trunk from about 1 month ago which have been installed with `pip` on both system.

```
Collecting cogent
  Downloading cogent-1.9.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 968kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UvtXdd/cogent/setup.py", line 154, in <module>
        CythonExtension("cogent.maths.spatial.ckd3"),
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 754, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 649, in create_extension_list
        for file in nonempty(extended_iglob(filepattern), "'%s' doesn't match any files" % filepattern):
      File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 103, in nonempty
        raise ValueError(error_msg)
    ValueError: 'cogent/align/_compare.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-UvtXdd/cogent/
```

**Comment by GavinHuttley** [comment]
I cannot reproduce on CentOS. What version of Cython is installed?

**Comment by miklou** [comment]
On the ArchLinux, I have the version 0.24 of `cython2`.

I used the environnment variable and got a success message.

**Comment by GavinHuttley** [comment]
That's puzzling, as that's the same version on my systems. Can you attach the result of
```bash
$ pip freeze > packs.txt
```

**Comment by miklou** [comment]
Here is the ArchLinux box result for `pip2 freeze`.
[packs.txt](https://github.com/pycogent/pycogent/files/333276/packs.txt)

I'm not sure the following is relevant but in case of...
I'm always priorizing packages in this order : 
1 - from the official repositories,
2 - from AUR (if it's required for another AUR package)
3 - from PyPI using the command `pip2`
4 - git repository using `pip` again.

I didn't really get into `virtualenv` so far.

The default python version under ArchLinux is python3, that's why I will always put the version at the end of the command, i.e.: `cython2`, `python2`, `pip2`.

But as I said, I'm also using a ubuntu box (14.04 LTS) which gave me the same error..

**Comment by EricDeveaud** [comment]
same problem here.
centos-6.8
python-2.7.3 
Cython-0.23.4 
also fail with 0.24.1

**Comment by prehensilecode** [comment]
I am experiencing the same issue.

The reason is that the [source tarball hosted at PyPI](https://pypi.python.org/pypi/cogent) does not contain any .pyx files - they just contain  .c files.

**Comment by guillermomarco** [comment]
I'm having the same problem on Ubuntu 16.04. Tried upgrading cython and numpy but still fails:
```
pip install --upgrade cogent
...
ValueError: 'cogent/align/_compare.pyx' doesn't match any file
```
Trying install from source:

```
Processing ./Downloads/pycogent-1.9.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 317, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 600, in _prepare_file
    req_to_install.check_if_exists()
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1011, in check_if_exists
    self.req.project_name
AttributeError: 'Requirement' object has no attribute 'project_name'
```

**Comment by QMuncaster** [comment]
I am having the same problem, but `DONT_USE_PYREX=1 pip install --upgrade cogent` gives me:
`  Failed building wheel for cogent`
...
'    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-v1LjI4/cogent/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-k_Cmtc-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-v1LjI4/cogent/
'

**Comment by GavinHuttley** [comment]
What OS and version are you on, what version of python, what version of pip.

Could you also post the entire traceback.

**Comment by QMuncaster** [comment]
Nevermind, I didn't have python-dev installed, but now it works. Thank you!

**Comment by maxogden** [comment]
I am experiencing the same issue, using pip/python2 from anaconda 5. `DONT_USE_PYREX=1 pip install cogent` worked for me

**Comment by GavinHuttley** [comment]
[cogent3](https://github.com/cogent3/cogent3) is the port of PyCogent to cogent3. Please see the [cogent3 docs](https://cogent3.org) for a description of how this is differs from PyCogent.
